markdown: redcarpet
rdiscount:
  extensions: [smart]
timezone: DE


redcarpet:
  syntax_highlighter: rouge


plugins:
  - jekyll-sitemap
  - jekyll-minifier

jekyll-minifier:
  exclude: '*.js'

permalink: /:title/

author: Matthias GÃ¼nther
email: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#109;&#97;&#116;&#116;&#104;&#105;&#97;&#115;&#64;&#112;&#97;&#100;&#114;&#105;&#110;&#111;&#98;&#111;&#111;&#107;&#46;&#99;&#111;&#109;"
twitter: https://twitter.com/padrinobook
url: https://padrinobook.com
title: PadrinoBook
description: PadrinoBook - The Guide To Master The Elegant Ruby Web Framework

# statistics
build: 6-19-2017
htmlpages: 600
images: 20
links: 271


# bitbucket
pmwiki_dropcaps_recipe: 2017-02-24
pmwiki_syntaxlove_recipe: 2017-02-26
pmwiki_twitter_recipe: 2017-02-26
pmwiki_linkicons_recipe: 2017-02-26
pmwiki_headlineimage_recipe: 2017-02-25

exclude:
  - 'README.md'
  - 'Gemfile.lock'
  - 'webpack.config.js'
  - 'bin'
  - 'Rakefile'
  - 'Gemfile'
  - 'tags'
  - 'bin'
  - 'node_modules'
  - 'package.json'
  - 'package-lock.json'
  - 'main.js'
  - 'main.js.map'


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
